token:
  secret: secret
server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
          
      routes:
      
        - id: user-service-rest
          uri: lb://user-service-rest
          predicates:
            Path=/api/v1/users/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            
        - id: mail-service-rest
          uri: lb://mail-service-rest
          predicates:
            Path=/api/v1/mail-sender/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            
        - id: teacher-service-rest
          uri: lb://teacher-service-rest
          predicates:
            Path=/api/v1/teachers/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        
        - id: lesson-service-rest
          uri: lb://lesson-service-rest
          predicates:
            Path=/api/v1/lessons/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            
        - id: comment-service-rest
          uri: lb://comment-service-rest
          predicates:
            Path=/api/v1/comments/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            
        - id: homework-service-rest
          uri: lb://homework-service-rest
          predicates:
            Path=/api/v1/homeworks/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin            
            
        - id: classroom-service-rest
          uri: lb://classroom-service-rest
          predicates:
            Path=/api/v1/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin         
         
        - id: auth-service-rest
          uri: lb://auth-service-rest
          predicates:
            Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            
management:
  security:
    enabled: false
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway    
