spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/homework_db
    username: postgres
    password: root

  #flyway properties
  flyway:
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/homework_db
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: false
    baseline-on-migrate: true
