server:
    port: 8081

spring:
    logging:
        level: debug
        
    # JPA properties
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            javax:
                persistence:
                    schema-generation:
                        create-source: metadata

token:
  secret: secret
