spring:

  #postgreSql properties
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/mail_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #flyway properties
  flyway:
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/mail_db
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: false
    baseline-on-migrate: true

