spring:
  datasource:
    url: jdbc:postgresql://postgresql_user_service/
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    user: postgres
    password: root
    url: jdbc:postgresql://postgresql_user_service/
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: false
    baseline-on-migrate: true
#     mixed: true
    schemas: user_service_rest

# user:
#   service:
#     feign:
#       url: "http://gateway-server/user-service-rest"
